services:
  - type: web
    name: trashsight-web
    env: python
    buildCommand: ""
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
